const { providedExerciseCatalog } = require("./providedExerciseCatalog");

const REVIEW_DATE = "2026-09-13";

const evidenceSources = [
  {
    name: "ACSM 2026 resistance training position stand summary",
    url: "https://acsm.org/resistance-training-guidelines-update-2026/",
    reviewedOn: REVIEW_DATE,
  },
  {
    name: "CDC adult physical activity guidance",
    url: "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html",
    reviewedOn: REVIEW_DATE,
  },
  {
    name: "American Heart Association warning signs",
    url: "https://www.heart.org/en/health-topics/heart-attack/warning-signs-of-a-heart-attack",
    reviewedOn: REVIEW_DATE,
  },
];

const defaultSafetyNotes = [
  "Use a load or pace that lets you keep controlled technique.",
  "Stop if you feel sharp pain, dizziness, chest pain, unusual shortness of breath, or loss of balance.",
  "This is general fitness guidance and does not replace advice from a doctor, physiotherapist, or qualified trainer.",
];

const noVerifiedVideo = {
  url: "",
  provider: "",
  sourceName: "Unavailable - needs manual video review before production use",
  status: "unavailable",
  lastValidated: "",
};

const youtubeTutorials = {
  "Bodyweight Squats": "https://www.youtube.com/embed/P-yaD24bUE8",
  "Dumbbell Squats": "https://www.youtube.com/embed/Xjo_fY9Hl9w",
  "Leg Press Machine": "https://www.youtube.com/embed/Aq5uxXrXq7c",
  "Leg Extension Machine": "https://www.youtube.com/embed/YyvSfVjQeL0",
  "Glute Bridges": "https://www.youtube.com/embed/OUgsJ8-Vi0E",
  "Bodyweight Hip Thrust": "https://www.youtube.com/embed/pF17m_CXfL0",
  "Hip Thrust Machine": "https://www.youtube.com/embed/UVucPKyQVLU",
  "Cable Kickbacks": "https://www.youtube.com/embed/5jJNfIlKTmg",
  "Reverse Lunges": "https://www.youtube.com/embed/xrPteyQLGAo",
  "Step-ups": "https://www.youtube.com/embed/dQqApCGd5Ss",
  "Side-Lying Leg Raises": "https://www.youtube.com/embed/jgh6sGwtTwk",
  "Abductor Machine": "https://www.youtube.com/embed/OjI5OpV6IWA",
  "Dumbbell Romanian Deadlift": "https://www.youtube.com/embed/jEy_czb3RKA",
  "Hamstring Curl Machine": "https://www.youtube.com/embed/t9sTSr-JYSs",
  "Standing Calf Raises": "https://www.youtube.com/embed/-M4-G8p8fmc",
  "Lat Pulldown Machine": "https://www.youtube.com/embed/AOpi-p0cJkc",
  "Seated Row Machine": "https://www.youtube.com/embed/TeFo51Q_Nsc",
  "Resistance Band Rows": "https://www.youtube.com/embed/Y3H17rshgZE",
  "Dumbbell Rows": "https://www.youtube.com/embed/6gvmcqr226U",
  "Chest Press Machine": "https://www.youtube.com/embed/sqNwDkUU_Ps",
  "Wall Push-ups": "https://www.youtube.com/embed/QpMTk21EmaM",
  "Push-ups": "https://www.youtube.com/embed/WDIpL0pjun0",
  "Shoulder Press Machine": "https://www.youtube.com/embed/3R14MnZbcpw",
  "Dumbbell Shoulder Press": "https://www.youtube.com/embed/e_f5oodNEcI",
  "Pike Push-ups": "https://www.youtube.com/embed/XckEEwa1BPI",
  "Cable Tricep Pushdown": "https://www.youtube.com/embed/2-LAMcpzODU",
  "Dumbbell Bicep Curl": "https://www.youtube.com/embed/ykJmrZ5v0Oo",
  "Cable Pallof Press": "https://www.youtube.com/embed/SY5lRzBPtM4",
  "Dead Bug": "https://www.youtube.com/embed/bxn9FBrt4-A",
  Plank: "https://www.youtube.com/embed/pSHjTRCQxIw",
  "Bicycle Crunches": "https://www.youtube.com/embed/9FGilxCbdz8",
  "Mountain Climbers": "https://www.youtube.com/embed/nmwgirgXLYM",
  "Jumping Jacks": "https://www.youtube.com/embed/c4DAnQ6DtF8",
  "Step Touch Intervals": "https://www.youtube.com/embed/8oTjg7ZXJok",
  "Treadmill Incline Walk": "https://www.youtube.com/embed/NAsObfFJXvE",
  "Brisk Walk": "https://www.youtube.com/embed/wQrV75N2BrI",
  ...Object.fromEntries(providedExerciseCatalog.map((exercise) => [exercise.name, exercise.videoUrl])),
};

const makeYouTubeVideo = (name) => {
  const url = youtubeTutorials[name];
  return url
    ? {
        url,
        provider: "YouTube",
        sourceName: "YouTube tutorial reference",
        status: "verified",
        lastValidated: REVIEW_DATE,
      }
    : noVerifiedVideo;
};

const makeExercise = ({
  name,
  primaryMuscles,
  secondaryMuscles = [],
  movementPattern,
  equipment,
  locations,
  difficulty = "Beginner",
  defaultSets,
  defaultReps,
  defaultRest,
  prescriptionType = "reps",
  instructions,
  formCue,
  commonMistakes,
  safetyNotes = defaultSafetyNotes,
  easierAlternatives = [],
  harderAlternatives = [],
  contraindications = [],
}) => ({
  name,
  primaryMuscles,
  secondaryMuscles,
  movementPattern,
  equipment,
  locations,
  difficulty,
  defaultSets,
  defaultReps,
  defaultRest,
  prescriptionType,
  instructions,
  formCue,
  commonMistakes,
  safetyNotes,
  easierAlternatives,
  harderAlternatives,
  contraindications,
  video: makeYouTubeVideo(name),
  evidenceSources,
  reviewedOn: REVIEW_DATE,
});

const exerciseDatabase = {
  "Bodyweight Squats": makeExercise({
    name: "Bodyweight Squats",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Squat",
    equipment: ["Bodyweight"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "60 seconds",
    instructions: ["Stand tall with feet about shoulder width.", "Sit the hips back and bend the knees under control.", "Stand by pressing through the whole foot."],
    formCue: "Keep your chest lifted and knees tracking over your toes.",
    commonMistakes: ["Knees collapsing inward.", "Heels lifting.", "Rushing the bottom position."],
    easierAlternatives: ["Chair Squat"],
    harderAlternatives: ["Dumbbell Squats"],
  }),
  "Dumbbell Squats": makeExercise({
    name: "Dumbbell Squats",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Squat",
    equipment: ["Dumbbells"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "75 seconds",
    instructions: ["Hold dumbbells securely.", "Squat with control.", "Stand tall without bouncing."],
    formCue: "Use a load that keeps the torso controlled.",
    commonMistakes: ["Choosing too much load.", "Letting the back round.", "Rushing reps."],
    easierAlternatives: ["Bodyweight Squats"],
    harderAlternatives: ["Leg Press Machine"],
  }),
  "Leg Press Machine": makeExercise({
    name: "Leg Press Machine",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    movementPattern: "Squat",
    equipment: ["Leg press machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "90 seconds",
    instructions: ["Set the seat so your back stays supported.", "Lower to a comfortable knee bend.", "Press up without locking the knees hard."],
    formCue: "Keep your lower back on the pad and knees tracking over toes.",
    commonMistakes: ["Lower back lifting.", "Knees caving in.", "Locking knees forcefully."],
    easierAlternatives: ["Bodyweight Squats"],
    harderAlternatives: ["Dumbbell Squats"],
  }),
  "Leg Extension Machine": makeExercise({
    name: "Leg Extension Machine",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    movementPattern: "Knee extension",
    equipment: ["Leg extension machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "60 seconds",
    instructions: ["Align your knees with the machine pivot.", "Extend the knees smoothly.", "Lower the pad with control."],
    formCue: "Use a light load and avoid snapping the knees straight.",
    commonMistakes: ["Kicking the weight up.", "Locking out aggressively.", "Letting the hips lift."],
    easierAlternatives: ["Step-ups"],
    harderAlternatives: ["Leg Press Machine"],
  }),
  "Glute Bridges": makeExercise({
    name: "Glute Bridges",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Hip extension",
    equipment: ["Bodyweight", "Mat"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "45 seconds",
    instructions: ["Lie on your back with knees bent.", "Drive through the heels to lift the hips.", "Pause briefly and lower with control."],
    formCue: "Squeeze the glutes without arching your lower back.",
    commonMistakes: ["Overextending the spine.", "Feet too far away.", "Moving too fast."],
    easierAlternatives: ["Bodyweight Hip Thrust"],
    harderAlternatives: ["Hip Thrust Machine"],
  }),
  "Bodyweight Hip Thrust": makeExercise({
    name: "Bodyweight Hip Thrust",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Hip extension",
    equipment: ["Bench or sturdy chair"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "60 seconds",
    instructions: ["Place upper back on a stable support.", "Plant feet and brace.", "Lift hips until the torso is level, then lower."],
    formCue: "Keep ribs down and chin tucked.",
    commonMistakes: ["Arching the back.", "Pushing through toes.", "Using an unstable surface."],
    easierAlternatives: ["Glute Bridges"],
    harderAlternatives: ["Hip Thrust Machine"],
  }),
  "Hip Thrust Machine": makeExercise({
    name: "Hip Thrust Machine",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Hip extension",
    equipment: ["Hip thrust machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "90 seconds",
    instructions: ["Set the pad and foot position first.", "Brace and lift the hips.", "Pause at the top and lower under control."],
    formCue: "Drive through heels and avoid lower-back extension.",
    commonMistakes: ["Flaring ribs.", "Using too much weight.", "Dropping quickly."],
    easierAlternatives: ["Glute Bridges"],
    harderAlternatives: [],
  }),
  "Cable Kickbacks": makeExercise({
    name: "Cable Kickbacks",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings"],
    movementPattern: "Hip extension",
    equipment: ["Cable machine", "Ankle strap"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "10-12 reps each side",
    defaultRest: "45 seconds",
    instructions: ["Attach the ankle strap.", "Brace and kick back from the hip.", "Return slowly without swinging."],
    formCue: "Keep your pelvis square and torso steady.",
    commonMistakes: ["Swinging.", "Arching the back.", "Rotating the hips."],
    easierAlternatives: ["Glute Bridges"],
    harderAlternatives: ["Hip Thrust Machine"],
  }),
  "Reverse Lunges": makeExercise({
    name: "Reverse Lunges",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Lunge",
    equipment: ["Bodyweight"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "8-10 reps each side",
    defaultRest: "60 seconds",
    instructions: ["Step back into a split stance.", "Lower with control.", "Press through the front foot to stand."],
    formCue: "Keep the front knee tracking over the toes.",
    commonMistakes: ["Pushing off the back foot too much.", "Losing balance.", "Collapsing the front knee inward."],
    easierAlternatives: ["Static Lunges"],
    harderAlternatives: ["Step-ups"],
  }),
  "Step-ups": makeExercise({
    name: "Step-ups",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Step",
    equipment: ["Stable step or bench"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "8-10 reps each side",
    defaultRest: "60 seconds",
    instructions: ["Place one foot on a stable step.", "Stand by driving through the lead foot.", "Lower with control."],
    formCue: "Use a step height that lets you control the knee.",
    commonMistakes: ["Pushing too much from the trailing leg.", "Using an unstable surface.", "Dropping down fast."],
    easierAlternatives: ["Bodyweight Squats"],
    harderAlternatives: ["Dumbbell Squats"],
  }),
  "Side-Lying Leg Raises": makeExercise({
    name: "Side-Lying Leg Raises",
    primaryMuscles: ["Glute medius", "Outer hip"],
    secondaryMuscles: ["Core"],
    movementPattern: "Hip abduction",
    equipment: ["Bodyweight", "Mat"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "10-12 reps each side",
    defaultRest: "45 seconds",
    instructions: ["Lie on your side with legs stacked.", "Lift the top leg without rolling the hips back.", "Lower slowly."],
    formCue: "Keep toes slightly forward and move slowly.",
    commonMistakes: ["Rolling the pelvis.", "Swinging the leg.", "Lifting too high."],
    easierAlternatives: ["Glute Bridges"],
    harderAlternatives: ["Band Lateral Walks"],
  }),
  "Abductor Machine": makeExercise({
    name: "Abductor Machine",
    primaryMuscles: ["Glute medius", "Outer hip"],
    secondaryMuscles: ["Glutes"],
    movementPattern: "Hip abduction",
    equipment: ["Abductor machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "45 seconds",
    instructions: ["Sit tall with knees against the pads.", "Press outward under control.", "Return slowly."],
    formCue: "Stay upright and avoid bouncing.",
    commonMistakes: ["Leaning back.", "Using momentum.", "Forcing painful range."],
    easierAlternatives: ["Side-Lying Leg Raises"],
    harderAlternatives: ["Band Lateral Walks"],
  }),
  "Dumbbell Romanian Deadlift": makeExercise({
    name: "Dumbbell Romanian Deadlift",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Back", "Core"],
    movementPattern: "Hip hinge",
    equipment: ["Dumbbells"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "75 seconds",
    instructions: ["Hold dumbbells close to the thighs.", "Hinge at the hips with soft knees.", "Stand by driving hips forward."],
    formCue: "Keep the back long and weights close.",
    commonMistakes: ["Squatting instead of hinging.", "Rounding the back.", "Letting weights drift forward."],
    contraindications: ["Current back pain or hamstring injury should be professionally assessed before hinging under load."],
    easierAlternatives: ["Glute Bridges"],
    harderAlternatives: ["Hamstring Curl Machine"],
  }),
  "Hamstring Curl Machine": makeExercise({
    name: "Hamstring Curl Machine",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Calves"],
    movementPattern: "Knee flexion",
    equipment: ["Hamstring curl machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "60 seconds",
    instructions: ["Adjust the pad above the ankles.", "Curl smoothly.", "Lower without dropping the load."],
    formCue: "Keep hips down and reps controlled.",
    commonMistakes: ["Jerking the weight.", "Lifting hips.", "Using partial range."],
    easierAlternatives: ["Glute Bridges"],
    harderAlternatives: ["Dumbbell Romanian Deadlift"],
  }),
  "Standing Calf Raises": makeExercise({
    name: "Standing Calf Raises",
    primaryMuscles: ["Calves"],
    secondaryMuscles: ["Feet and ankles"],
    movementPattern: "Ankle plantar flexion",
    equipment: ["Bodyweight or machine"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "12-20 reps",
    defaultRest: "45 seconds",
    instructions: ["Stand tall.", "Rise onto the balls of the feet.", "Lower slowly."],
    formCue: "Avoid bouncing at the bottom.",
    commonMistakes: ["Rolling ankles outward.", "Rushing reps.", "Locking knees hard."],
    easierAlternatives: ["Bodyweight Squats"],
    harderAlternatives: ["Step-ups"],
  }),
  "Lat Pulldown Machine": makeExercise({
    name: "Lat Pulldown Machine",
    primaryMuscles: ["Lats", "Upper back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical pull",
    equipment: ["Lat pulldown machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "75 seconds",
    instructions: ["Grip the bar and sit tall.", "Pull to the upper chest.", "Return with control."],
    formCue: "Keep shoulders down and avoid leaning far back.",
    commonMistakes: ["Pulling behind the neck.", "Swinging the torso.", "Shrugging."],
    easierAlternatives: ["Resistance Band Rows"],
    harderAlternatives: ["Seated Row Machine"],
  }),
  "Seated Row Machine": makeExercise({
    name: "Seated Row Machine",
    primaryMuscles: ["Upper back", "Lats"],
    secondaryMuscles: ["Biceps", "Rear delts"],
    movementPattern: "Horizontal pull",
    equipment: ["Seated row machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "75 seconds",
    instructions: ["Sit tall with chest supported if available.", "Pull handles toward ribs.", "Return slowly."],
    formCue: "Squeeze shoulder blades without shrugging.",
    commonMistakes: ["Rounding the back.", "Yanking with arms.", "Leaning back excessively."],
    easierAlternatives: ["Resistance Band Rows"],
    harderAlternatives: ["Dumbbell Rows"],
  }),
  "Resistance Band Rows": makeExercise({
    name: "Resistance Band Rows",
    primaryMuscles: ["Upper back", "Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal pull",
    equipment: ["Resistance band"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "60 seconds",
    instructions: ["Anchor the band securely.", "Pull toward ribs.", "Return slowly."],
    formCue: "Keep shoulders away from ears.",
    commonMistakes: ["Unsafe anchor.", "Shrugging.", "Letting the band snap back."],
    easierAlternatives: ["Band Pull Aparts"],
    harderAlternatives: ["Dumbbell Rows"],
  }),
  "Dumbbell Rows": makeExercise({
    name: "Dumbbell Rows",
    primaryMuscles: ["Upper back", "Lats"],
    secondaryMuscles: ["Biceps", "Core"],
    movementPattern: "Horizontal pull",
    equipment: ["Dumbbells"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps each side",
    defaultRest: "75 seconds",
    instructions: ["Hinge and support yourself if needed.", "Pull the dumbbell toward the waist.", "Lower under control."],
    formCue: "Keep ribs and hips square.",
    commonMistakes: ["Twisting the torso.", "Rounding the back.", "Yanking the weight."],
    easierAlternatives: ["Resistance Band Rows"],
    harderAlternatives: ["Seated Row Machine"],
  }),
  "Chest Press Machine": makeExercise({
    name: "Chest Press Machine",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    movementPattern: "Horizontal push",
    equipment: ["Chest press machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "75 seconds",
    instructions: ["Set handles at chest height.", "Press forward under control.", "Return without losing shoulder position."],
    formCue: "Keep wrists stacked over elbows.",
    commonMistakes: ["Shrugging.", "Overarching.", "Bouncing at the back."],
    easierAlternatives: ["Wall Push-ups"],
    harderAlternatives: ["Push-ups"],
  }),
  "Wall Push-ups": makeExercise({
    name: "Wall Push-ups",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    movementPattern: "Horizontal push",
    equipment: ["Wall"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "60 seconds",
    instructions: ["Place hands on a wall.", "Lower chest toward the wall.", "Press away with control."],
    formCue: "Keep the body in one long line.",
    commonMistakes: ["Hips sagging.", "Elbows flaring hard.", "Rushing."],
    easierAlternatives: [],
    harderAlternatives: ["Push-ups"],
  }),
  "Push-ups": makeExercise({
    name: "Push-ups",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps", "Core"],
    movementPattern: "Horizontal push",
    equipment: ["Bodyweight"],
    locations: ["Home", "Gym"],
    difficulty: "Intermediate",
    defaultSets: 3,
    defaultReps: "6-12 reps",
    defaultRest: "75 seconds",
    instructions: ["Start in a strong plank.", "Lower chest toward the floor.", "Press up without sagging."],
    formCue: "Brace like a plank through every rep.",
    commonMistakes: ["Sagging hips.", "Half reps.", "Neck reaching forward."],
    easierAlternatives: ["Wall Push-ups"],
    harderAlternatives: ["Pike Push-ups"],
  }),
  "Shoulder Press Machine": makeExercise({
    name: "Shoulder Press Machine",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps", "Upper chest"],
    movementPattern: "Vertical push",
    equipment: ["Shoulder press machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "75 seconds",
    instructions: ["Set the seat for a comfortable start.", "Press overhead.", "Lower under control."],
    formCue: "Keep ribs stacked and avoid shrugging.",
    commonMistakes: ["Arching the back.", "Locking out aggressively.", "Shrugging."],
    easierAlternatives: ["Dumbbell Shoulder Press"],
    harderAlternatives: ["Pike Push-ups"],
  }),
  "Dumbbell Shoulder Press": makeExercise({
    name: "Dumbbell Shoulder Press",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps", "Core"],
    movementPattern: "Vertical push",
    equipment: ["Dumbbells"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps",
    defaultRest: "75 seconds",
    instructions: ["Hold dumbbells at shoulder height.", "Press overhead.", "Lower with control."],
    formCue: "Do not lean back to finish reps.",
    commonMistakes: ["Overarching.", "Pressing unevenly.", "Using too much load."],
    easierAlternatives: ["Wall Push-ups"],
    harderAlternatives: ["Shoulder Press Machine"],
  }),
  "Pike Push-ups": makeExercise({
    name: "Pike Push-ups",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps", "Core"],
    movementPattern: "Vertical push",
    equipment: ["Bodyweight"],
    locations: ["Home", "Gym"],
    difficulty: "Intermediate",
    defaultSets: 3,
    defaultReps: "6-10 reps",
    defaultRest: "75 seconds",
    instructions: ["Start with hips high.", "Lower the head toward the floor.", "Press back up with control."],
    formCue: "Keep elbows controlled and neck relaxed.",
    commonMistakes: ["Crashing down.", "Turning it into a regular push-up.", "Forcing shoulder range."],
    easierAlternatives: ["Dumbbell Shoulder Press"],
    harderAlternatives: [],
  }),
  "Cable Tricep Pushdown": makeExercise({
    name: "Cable Tricep Pushdown",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Shoulders"],
    movementPattern: "Elbow extension",
    equipment: ["Cable machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "60 seconds",
    instructions: ["Set elbows near your sides.", "Press the handle down.", "Return slowly."],
    formCue: "Keep elbows pinned and shoulders quiet.",
    commonMistakes: ["Leaning over.", "Swinging.", "Letting elbows drift."],
    easierAlternatives: ["Wall Push-ups"],
    harderAlternatives: ["Push-ups"],
  }),
  "Dumbbell Bicep Curl": makeExercise({
    name: "Dumbbell Bicep Curl",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    movementPattern: "Elbow flexion",
    equipment: ["Dumbbells"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "10-15 reps",
    defaultRest: "60 seconds",
    instructions: ["Hold dumbbells at sides.", "Curl without swinging.", "Lower slowly."],
    formCue: "Keep elbows close and wrists neutral.",
    commonMistakes: ["Swinging the torso.", "Shrugging.", "Dropping the weights."],
    easierAlternatives: ["Resistance Band Curls"],
    harderAlternatives: [],
  }),
  "Cable Pallof Press": makeExercise({
    name: "Cable Pallof Press",
    primaryMuscles: ["Deep core", "Obliques"],
    secondaryMuscles: ["Glutes", "Shoulders"],
    movementPattern: "Anti-rotation",
    equipment: ["Cable machine"],
    locations: ["Gym"],
    defaultSets: 3,
    defaultReps: "8-10 reps each side",
    defaultRest: "45 seconds",
    instructions: ["Stand side-on to the cable.", "Brace and press the handle out.", "Resist rotation as you return."],
    formCue: "Keep ribs stacked and hips square.",
    commonMistakes: ["Twisting toward the cable.", "Using too much load.", "Holding breath."],
    easierAlternatives: ["Dead Bug"],
    harderAlternatives: ["Plank"],
  }),
  "Dead Bug": makeExercise({
    name: "Dead Bug",
    primaryMuscles: ["Deep core"],
    secondaryMuscles: ["Hip flexors", "Shoulders"],
    movementPattern: "Anti-extension",
    equipment: ["Bodyweight", "Mat"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "6-10 reps each side",
    defaultRest: "45 seconds",
    instructions: ["Lie on your back with arms and knees up.", "Brace gently.", "Lower opposite arm and leg under control."],
    formCue: "Keep the low back from arching.",
    commonMistakes: ["Moving too fast.", "Arching the back.", "Holding breath."],
    easierAlternatives: ["Plank"],
    harderAlternatives: ["Cable Pallof Press"],
  }),
  "Plank": makeExercise({
    name: "Plank",
    primaryMuscles: ["Deep core"],
    secondaryMuscles: ["Shoulders", "Glutes"],
    movementPattern: "Anti-extension",
    equipment: ["Bodyweight", "Mat"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "20-45 seconds",
    defaultRest: "45 seconds",
    prescriptionType: "duration",
    instructions: ["Set elbows under shoulders.", "Brace and hold a straight line.", "Breathe steadily."],
    formCue: "Stop the set before your hips sag.",
    commonMistakes: ["Sagging hips.", "Holding breath.", "Shrugging."],
    easierAlternatives: ["Knee Plank"],
    harderAlternatives: ["Shoulder Taps"],
  }),
  "Bicycle Crunches": makeExercise({
    name: "Bicycle Crunches",
    primaryMuscles: ["Abs", "Obliques"],
    secondaryMuscles: ["Hip flexors"],
    movementPattern: "Trunk rotation",
    equipment: ["Bodyweight", "Mat"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "8-12 reps each side",
    defaultRest: "45 seconds",
    instructions: ["Lie back with hands light behind head.", "Rotate opposite elbow toward knee.", "Move slowly side to side."],
    formCue: "Rotate through the torso, not by pulling the neck.",
    commonMistakes: ["Yanking the neck.", "Rushing.", "Letting the low back arch."],
    easierAlternatives: ["Dead Bug"],
    harderAlternatives: ["Plank"],
  }),
  "Mountain Climbers": makeExercise({
    name: "Mountain Climbers",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders", "Hip flexors", "Cardiovascular system"],
    movementPattern: "Conditioning",
    equipment: ["Bodyweight"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "20-30 seconds",
    defaultRest: "45 seconds",
    prescriptionType: "duration",
    instructions: ["Start in a plank.", "Drive one knee in at a time.", "Keep a steady rhythm."],
    formCue: "Keep shoulders stacked and land quietly.",
    commonMistakes: ["Bouncing hips.", "Going too fast.", "Holding breath."],
    easierAlternatives: ["Slow Mountain Climbers"],
    harderAlternatives: [],
  }),
  "Jumping Jacks": makeExercise({
    name: "Jumping Jacks",
    primaryMuscles: ["Cardiovascular system"],
    secondaryMuscles: ["Calves", "Shoulders"],
    movementPattern: "Conditioning",
    equipment: ["Bodyweight"],
    locations: ["Home", "Gym"],
    defaultSets: 3,
    defaultReps: "20-45 seconds",
    defaultRest: "45 seconds",
    prescriptionType: "duration",
    instructions: ["Jump feet out as arms rise.", "Return to start.", "Keep landings soft."],
    formCue: "Switch to step jacks if impact is uncomfortable.",
    commonMistakes: ["Hard landings.", "Poor rhythm.", "Going all-out too soon."],
    easierAlternatives: ["Step Touch Intervals"],
    harderAlternatives: ["Mountain Climbers"],
  }),
  "Step Touch Intervals": makeExercise({
    name: "Step Touch Intervals",
    primaryMuscles: ["Cardiovascular system"],
    secondaryMuscles: ["Hips", "Calves"],
    movementPattern: "Low-impact conditioning",
    equipment: ["Bodyweight"],
    locations: ["Home", "Gym"],
    defaultSets: 1,
    defaultReps: "10-20 minutes",
    defaultRest: "As needed",
    prescriptionType: "duration",
    instructions: ["Step side to side rhythmically.", "Add arm reach if comfortable.", "Stay conversational unless prescribed otherwise."],
    formCue: "Keep steps light and the floor clear.",
    commonMistakes: ["Dragging feet.", "Holding breath.", "Moving too fast for balance."],
    easierAlternatives: ["Brisk Walk"],
    harderAlternatives: ["Jumping Jacks"],
  }),
  "Treadmill Incline Walk": makeExercise({
    name: "Treadmill Incline Walk",
    primaryMuscles: ["Cardiovascular system"],
    secondaryMuscles: ["Glutes", "Calves"],
    movementPattern: "Low-impact conditioning",
    equipment: ["Treadmill"],
    locations: ["Gym"],
    defaultSets: 1,
    defaultReps: "10-20 minutes",
    defaultRest: "As needed",
    prescriptionType: "duration",
    instructions: ["Set a modest incline.", "Walk tall with relaxed arms.", "Keep the pace conversational to moderately challenging."],
    formCue: "Avoid leaning on the rails.",
    commonMistakes: ["Starting too steep.", "Holding the rails.", "Hunching forward."],
    easierAlternatives: ["Brisk Walk"],
    harderAlternatives: [],
  }),
  "Brisk Walk": makeExercise({
    name: "Brisk Walk",
    primaryMuscles: ["Cardiovascular system"],
    secondaryMuscles: ["Legs"],
    movementPattern: "Low-impact conditioning",
    equipment: ["Walking shoes"],
    locations: ["Home", "Gym"],
    defaultSets: 1,
    defaultReps: "10-20 minutes",
    defaultRest: "As needed",
    prescriptionType: "duration",
    instructions: ["Walk at a pace that raises breathing but still allows conversation.", "Keep posture tall.", "Slow down to cool down."],
    formCue: "Build duration gradually.",
    commonMistakes: ["Skipping warm-up.", "Increasing too quickly.", "Ignoring symptoms."],
    easierAlternatives: ["Step Touch Intervals"],
    harderAlternatives: ["Treadmill Incline Walk"],
  }),
};

for (const exercise of providedExerciseCatalog) {
  if (!exerciseDatabase[exercise.name]) {
    exerciseDatabase[exercise.name] = makeExercise({
      name: exercise.name,
      primaryMuscles: exercise.primaryMuscles,
      secondaryMuscles: exercise.secondaryMuscles,
      movementPattern: exercise.movementPattern,
      equipment: [exercise.equipment],
      locations: exercise.locations,
      difficulty: exercise.difficulty,
      defaultSets: exercise.defaultSets,
      defaultReps: exercise.defaultReps,
      defaultRest: exercise.defaultRest,
      prescriptionType: exercise.prescriptionType,
      instructions: exercise.instructions,
      formCue: exercise.formCue,
      commonMistakes: exercise.commonMistakes,
    });
  }
}

const exerciseAliases = {
  "bodyweight squat": "Bodyweight Squats",
  "bodyweight squats": "Bodyweight Squats",
  "chair squat": "Bodyweight Squats",
  "wall squats": "Bodyweight Squats",
  "jump squats": "Bodyweight Squats",
  "squat reach": "Bodyweight Squats",
  "dumbbell squat": "Dumbbell Squats",
  "dumbbell squats": "Dumbbell Squats",
  "dumbbell squat to press": "Dumbbell Squats",
  "leg press": "Leg Press Machine",
  "leg press machine": "Leg Press Machine",
  "leg extension": "Leg Extension Machine",
  "leg extension machine": "Leg Extension Machine",
  "glute bridge": "Glute Bridges",
  "glute bridges": "Glute Bridges",
  "single-leg glute bridges": "Glute Bridges",
  "weighted glute bridge": "Glute Bridges",
  "bodyweight hip thrust": "Bodyweight Hip Thrust",
  "hip thrust machine": "Hip Thrust Machine",
  "cable kickback": "Cable Kickbacks",
  "cable kickbacks": "Cable Kickbacks",
  "donkey kick": "Glute Bridges",
  "reverse lunge": "Reverse Lunges",
  "reverse lunges": "Reverse Lunges",
  "static lunges": "Reverse Lunges",
  "step-up": "Step-ups",
  "step up": "Step-ups",
  "step-ups": "Step-ups",
  "side-lying leg raise": "Side-Lying Leg Raises",
  "side-lying leg raises": "Side-Lying Leg Raises",
  "band lateral walks": "Side-Lying Leg Raises",
  "abductor machine": "Abductor Machine",
  "dumbbell romanian deadlift": "Dumbbell Romanian Deadlift",
  "hamstring curl machine": "Hamstring Curl Machine",
  "standing calf raise": "Standing Calf Raises",
  "standing calf raises": "Standing Calf Raises",
  "lat pulldown": "Lat Pulldown Machine",
  "lat pulldown machine": "Lat Pulldown Machine",
  "seated row": "Seated Row Machine",
  "seated row machine": "Seated Row Machine",
  "resistance band row": "Resistance Band Rows",
  "resistance band rows": "Resistance Band Rows",
  "band pull aparts": "Resistance Band Rows",
  "dumbbell row": "Dumbbell Rows",
  "dumbbell rows": "Dumbbell Rows",
  "chest press machine": "Chest Press Machine",
  "wall push up": "Wall Push-ups",
  "wall push-up": "Wall Push-ups",
  "wall push-ups": "Wall Push-ups",
  "incline push-ups": "Wall Push-ups",
  "knee push-ups": "Wall Push-ups",
  "push up": "Push-ups",
  "push-up": "Push-ups",
  "push-ups": "Push-ups",
  "shoulder press machine": "Shoulder Press Machine",
  "dumbbell shoulder press": "Dumbbell Shoulder Press",
  "pike push-up": "Pike Push-ups",
  "pike push-up hold": "Pike Push-ups",
  "pike push-ups": "Pike Push-ups",
  "cable tricep pushdown": "Cable Tricep Pushdown",
  "bench dips": "Cable Tricep Pushdown",
  "chair dips": "Cable Tricep Pushdown",
  "dumbbell bicep curl": "Dumbbell Bicep Curl",
  "resistance band curl": "Dumbbell Bicep Curl",
  "resistance band curls": "Dumbbell Bicep Curl",
  "water bottle curls": "Dumbbell Bicep Curl",
  "cable pallof press": "Cable Pallof Press",
  "pallof press": "Cable Pallof Press",
  "cable woodchop": "Cable Pallof Press",
  "dead bug": "Dead Bug",
  "deadbug": "Dead Bug",
  "plank": "Plank",
  "marching plank": "Plank",
  "knee plank": "Plank",
  "shoulder taps": "Plank",
  "bicycle crunch": "Bicycle Crunches",
  "bicycle crunches": "Bicycle Crunches",
  "machine crunch": "Bicycle Crunches",
  "mountain climber": "Mountain Climbers",
  "mountain climbers": "Mountain Climbers",
  "slow mountain climbers": "Mountain Climbers",
  "jumping jacks": "Jumping Jacks",
  "high knee march": "Jumping Jacks",
  "bike intervals": "Jumping Jacks",
  "step touch intervals": "Step Touch Intervals",
  "incline treadmill walk": "Treadmill Incline Walk",
  "treadmill incline walk": "Treadmill Incline Walk",
  "brisk walk": "Brisk Walk",
};

for (const exercise of providedExerciseCatalog) {
  const aliasKey = exercise.name.toLowerCase();
  if (!exerciseAliases[aliasKey]) exerciseAliases[aliasKey] = exercise.name;
}

module.exports = {
  REVIEW_DATE,
  defaultSafetyNotes,
  evidenceSources,
  exerciseAliases,
  exerciseDatabase,
  providedExerciseCatalog,
  youtubeTutorials,
};
